name: Create SDK

on:
  workflow_dispatch:
    inputs:
      ipsw_device:
        description: 'The device ID to download the IPSW for, e.g. "iPhone11,2"'
        required: true
        type: string
      ipsw_version:
        description: 'The version to download the IPSW for, e.g. "16.5"'
        required: true
        type: string
      dsc_basename:
        description: 'The basename for the dyld_shared_cache in the IPSW'
        required: true
        type: string
      xcrun_sdk_name:
        description: 'The value to pass to "xcrun --sdk", e.g. "iphoneos"'
        required: true
        type: string
        default: 'iphoneos'
      full_sdk_name:
        description: 'The full name of the output SDK, e.g. "iPhoneOS16.5"'
        required: true
        type: string

jobs:
  create:
    # https://github.com/actions/runner-images/blob/main/images/macos
    runs-on: macos-14
    # needed to be able to push to the repo
    permissions:
      contents: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Clone tbd
        uses: actions/checkout@v4
        with:
          repository: leptos-null/tbd
          ref: f0ae164d76b7bb802bbdf8ef758cc5637fac0fa1 # pinned, leptos/source-platform
          path: tbd

      - name: Build tbd
        run: |
          cd tbd
          make bin/tbd

      - name: Install blacktop/ipsw
        run: brew install blacktop/tap/ipsw

      - name: Install aria2
        run: brew install aria2
